[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
;serial monitoring settings
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
;upload settings
upload_speed = 921600
;build settings
build_flags =
    -D CONFIG_LOG_DEFAULT_LEVEL_INFO=1
; ESP-IDF specific settings
board_build.flash_mode = dio
;include extra components from the "components" directory
board_build.cmake_extra_args = 
    -DEXTRA_COMPONENT_DIRS=components